### ISSUE TITLE
Add unit tests for source code

### ISSUE THREAD

**Issue by bigsergey** [bigsergey/filenamelint#6]
Add unit tests to improve code quality

**Comment by bigsergey** [comment]
```js
import glob from 'fast-glob';

import lintFiles from './lint-files';

glob('**/*', { ignore: ['node_modules', 'README.md', 'CHANGELOG.md', 'LICENSE'] })
  .then(files => {
    const errorMessages = lintFiles(files);

    if (errorMessages.length > 0) {
      errorMessages.forEach(message => console.error(message));
      process.exit(1);
    } else {
      console.log('Success!!');
      process.exit(0);
    }
  })
  .catch(error => {
    console.error(error);
    process.exit(1);
  });
```

@erykpiast @adrianmroz  What is the best way to test code above? 

Mock process.exit in unit tests with Jest?
Maybe move promise with glob to separate file and set onSuccess and onError callback?
Does it make sense to test if the globe finds all files?

**Comment by erykpiast** [comment]
I suppose I'd to move the logic to separate file, exporting a function returning a promise (probably a promise of exit codes?). Then, in the main file you could run it simply like this:

```js
import main from './main';

main().then(process.exit);
```

A code like this doesn't have to be tested.

Testing the `glob` function itself doesn't make sense, it's not your responsibility. You should mock it.
